# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: apidb
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipass
    # (this is just an example, not intended to be a production configuration)
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
  # pc=8081,container=8080
    ports:
      - "8081:8080"

  redis:
    image: redis:7.4
    restart: always
    ports:
      - "6379:6379"