spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:apidb}
    username: ${DB_USER:apiuser}
    password: ${DB_PASS:apipass}
  data:
    redis:
    host: ${CACHE_HOST:localhost}
    port: ${CACHE_PORT:6379}
    password: ${CACHE_PASS:}
logging:
  level:
    com.example.blog.repository: DEBUG
    org.springframework.security: TRACE
    org.springframework.data.redis: TRACE
    org.springframework.session: TRACE
    org.springframework.web: TRACE
server:
  servlet:
    session:
      timeout: 3600s # 実験用にとても短い3600秒に設定