openapi: 3.0.3
info:
  title: Blog API Documentation
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Local development server
tags:
  - name: csrf-protection
    description: CSRF攻撃からアプリケーションを保護するためのAPI
  - name: users
    description: ユーザー情報のAPI
paths:
  # GET /csrf-cookie
  /csrf-cookie:
    get:
      tags: [ csrf-protection ]
      operationId: getCsrfCookie
      summary: CSRF Cookieの取得
      description: |
        リクエストに成功すると、204 No Content のレスポンスが返ります。
        このレスポンスのSet-Cookie ヘッダーにXSRF-TOKEN が含まれています。
        POST リクエストを実行するときは、受け取ったXSRF-TOKEN の値をX-XSRF-TOKEN ヘッダーに設定する必要があります。
        XSRF-TOKEN の値はPOST リクエストの度に取得し直す必要はなく、同じ値を何度も使うことができます。
      responses:
        '204':
          description: No Content
          headers:
            Set-Cookie:
              description: CSRF対策に利用するXSRF-TOKENというCookieが含まれています。
              schema:
                type: string
                example: XSRF-TOKEN=4ee8188f-2873-46cb-937f-7464ebf143e7; Path=/
          content: {}
        '500':
          $ref: "#/components/responses/InternalServerErrorResponse"
  /users:
    post:
      description: ユーザーを登録します
      tags: [users]
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserForm"
      responses:
        '201':
          description: Created
components:
  schemas:
    InternalServerError:
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
          format: int32
          default: 500
        detail:
          type: string
        instance:
          type: string
          format: uri
    UserForm:
      type: object
      required:
        - username
        - password
      properties:
        username:
          description: >
            ユーザー名。
            使用できる文字は半角英小文字と数字、およびハイフン、アンダースコア、ドットです。
            長さは3文字以上32文字以内です。
            ハイフン・アンダースコア・ドットはユーザー名の先頭と末尾に使用できません。
          type: string
          minLength: 3
          maxLength: 32
          example: username123
        password:
          description: パスワード。10文字以上255文字以内。
          type: string
          format: password
          minLength: 10
          maxLength: 255
          example: password123
  responses:
    InternalServerErrorResponse:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/InternalServerError"
